### ISSUE TITLE
SUPER CODE

### ISSUE THREAD

**Issue by afonina-anastasia** [AleksLobzov/predict#1]
PRIVET, NE RABOTAET VASHA  SSILKA Пример реализации модели с использованием класса приведен по адресу http://alobzov.pythonanywhere.com/network/, mono kak-to ehe poluchit realizaciju?

**Comment by alobzov** [comment]
Привет! Демо-стенд выключен. Однако, при необходимости, можно самостоятельно развернуть приложение на pythonanywhere.com. Там есть бесплатный доступ

**Comment by alobzov** [comment]
Привет! Демо-стенд выключен. Однако, при необходимости, можно самостоятельно развернуть приложение на pythonanywhere.com. Там есть бесплатный доступ
